version: "3.9"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    networks:
      - mynetwork
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge