version: "3.9"
services:
  web:
    image: nginx
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
